/**
 * Builds electrician-intake.html from intake-template.html + questions.js.
 *
 *   node build-html.js
 *
 * The template holds the chrome, the styling and the page logic. This script
 * drops the canonical question set into it. Edit the template for how the page
 * behaves, questions.js for what it asks — never the generated file.
 *
 * Publishing the result is a separate, manual step. See HANDOVER.md: it has to
 * go to the artifact URL the client already has, or their link stops working.
 */
const fs = require('fs');
const path = require('path');
const { SECTIONS, counts, validate, priorityPhrase } = require('./questions');

// Referenced by char code so the raw characters never appear in this file.
const LS = String.fromCharCode(0x2028);
const PS = String.fromCharCode(0x2029);

const TEMPLATE = path.join(__dirname, 'intake-template.html');
const OUT = path.join(__dirname, 'electrician-intake.html');
const TOKEN = 'var SECTIONS = /*__QUESTIONS__*/ null;';

validate();

const tpl = fs.readFileSync(TEMPLATE, 'utf8');
if (!tpl.includes(TOKEN)) {
  throw new Error(`${path.basename(TEMPLATE)} has no "${TOKEN}" placeholder — did someone edit the template?`);
}

/**
 * Serialise for embedding in an inline <script>. Two things bite here:
 * "</script>" inside any string would end the block early, and U+2028/U+2029
 * are legal in JSON but were illegal in JS string literals before ES2019.
 */
function embed(value) {
  return JSON.stringify(value, null, 2)
    .replace(/<\//g, '<\\/')
    .replace(new RegExp("[" + LS + PS + "]", "g"), function (m) {
      return "\\u" + m.charCodeAt(0).toString(16);
    });
}

const c = counts();
const banner = [
  '/* ----------------------------------------------------------------',
  '   GENERATED by build-html.js from questions.js — do not edit here.',
  `   ${c.sections} sections · ${c.questions} questions · ${c.blockers} flagged as blockers`,
  '   ---------------------------------------------------------------- */',
].join('\n  ');

const PRIORITY_TOKEN = '<!--__PRIORITY__-->';
if (!tpl.includes(PRIORITY_TOKEN)) {
  throw new Error(`${path.basename(TEMPLATE)} has no ${PRIORITY_TOKEN} placeholder — the intro would name sections from memory`);
}

const out = tpl
  .replace(TOKEN, `${banner}\n  var SECTIONS = ${embed(SECTIONS)};`)
  .replace(PRIORITY_TOKEN, priorityPhrase());

fs.writeFileSync(OUT, out);
console.log(`wrote ${path.basename(OUT)}  (${Math.round(out.length / 1024)} KB)  `
  + `${c.sections} sections, ${c.questions} questions, ${c.blockers} blockers`);
