/**
 * Builds build-intake-form.gs from questions.js.
 *
 *   node build-gs.js
 *
 * The output is a single self-contained file to paste into script.google.com.
 * It has to stay self-contained — Apps Script cannot require() anything — which
 * is why the question set is baked in rather than imported.
 *
 * Google Forms has no separate tel / email / url field type, so those become
 * plain text questions. It does have a native "Other:" option on checkboxes,
 * which is what `other: true` turns on.
 */
const fs = require('fs');
const path = require('path');
const { SECTIONS, counts, validate, priorityPhrase } = require('./questions');

// Referenced by char code so the raw characters never appear in this file.
const LS = String.fromCharCode(0x2028);
const PS = String.fromCharCode(0x2029);

const OUT = path.join(__dirname, 'build-intake-form.gs');

validate();
const c = counts();

// Only what the Form actually uses. Dropping the rest keeps the pasted file
// readable and avoids implying the Form honours `ph` or `otherLabel`, which it
// cannot. `many` + other:true becomes Google's own "Other:" row.
const forForm = SECTIONS.map((s) => ({
  n: s.n,
  title: s.title,
  why: s.why,
  fields: s.fields.map((f) => {
    const out = { t: ['one', 'many', 'area'].includes(f.t) ? f.t : 'text', label: f.label };
    if (f.r) out.r = true;
    if (f.hint) out.hint = f.hint;
    if (f.opts) out.opts = f.opts;
    if (f.other) out.other = true;
    return out;
  }),
}));

const header = `/**
 * Electrician website intake — Google Form generator
 * -------------------------------------------------
 * GENERATED by build-gs.js from questions.js. Do not edit this file; edit
 * questions.js and re-run the build, or the web page and the Word version will
 * drift away from this one. (That has already happened once — see HANDOVER.md.)
 *
 * Builds a ${c.sections}-section Google Form with ${c.questions} questions, plus a linked
 * spreadsheet that collects the answers.
 *
 * HOW TO RUN
 *   1. Go to script.google.com and click New project.
 *   2. Delete whatever is in the editor, paste this whole file in.
 *   3. Press Save, then Run. Pick buildIntakeForm if asked which function.
 *   4. Google will ask you to authorise it — it needs permission to create
 *      a form and a spreadsheet in your own Drive. Click through the
 *      "unverified app" warning via Advanced > Go to project.
 *   5. Open the Execution log. It prints three links: the form to send out,
 *      the editor, and the responses spreadsheet. The log stays empty until the
 *      run finishes, because Logger.log buffers — allow one to three minutes
 *      for roughly ${forForm.reduce((n, s) => n + s.fields.length, 0) + forForm.length} items.
 *   6. On the Responses tab, open the three-dot menu and turn on
 *      "Get email notifications for new responses".
 *
 * Running it again builds a BRAND NEW form and sheet. Delete the old pair from
 * Drive first, or you will end up sending the client the wrong link.
 *
 * A NOTE ON REQUIRED QUESTIONS
 *   Nothing is marked required. Google Forms refuses to submit at all while
 *   a required answer is blank, and on a ${c.questions}-question form filled in over
 *   several sittings that turns one unknown licence number into an abandoned
 *   form. The ${c.blockers} questions that block the build are marked with a star in
 *   the title instead, and called out on the intro page. Chase those.
 */

var FORM_TITLE = 'Electrician Website — Build Brief';

var FORM_INTRO = [
  'Everything needed to build your website, in one pass.',
  '',
  'Fill in what you know. Skip anything that does not apply — a half-answer',
  'beats a blank, because "not sure" tells us what to chase.',
  '',
  'Questions marked with a star (*) are the ones that actually block the',
  'build. Four things stall these projects more than anything else:',
  'no usable job photos, no licence and insurance numbers, nobody can log',
  'in to the domain, and nobody has decided who writes the words. If you only',
  'do a few sections, do ' + priorityPhrase() + '.',
  '',
  'You can come back to it — when you submit, keep the "Edit your response"',
  'link that appears, and you can carry on later or correct anything.'
].join('\\n');

var CONFIRMATION = [
  'Got it — thank you.',
  '',
  'Keep the "Edit your response" link above. It lets you come back and fill',
  'in anything you skipped, or fix something you got wrong, without',
  'starting again.'
].join('\\n');

/**
 * t: text | area | one | many
 * r: true  -> blocks the build (rendered with a leading star)
 * other:   -> checkbox question gets Google's native "Other:" row
 */
var SECTIONS = `;

const footer = `;


function buildIntakeForm() {
  var form = FormApp.create(FORM_TITLE);
  form.setDescription(FORM_INTRO);
  form.setConfirmationMessage(CONFIRMATION);
  form.setProgressBar(true);
  form.setAllowResponseEdits(true);
  form.setShowLinkToRespondAgain(false);
  form.setCollectEmail(false);

  // Workspace-only settings. Harmless to skip on a personal account.
  try { form.setRequireLogin(false); } catch (e) {}

  var starred = 0;
  var total = 0;

  SECTIONS.forEach(function (section) {
    form.addPageBreakItem()
      .setTitle(section.n + '. ' + section.title)
      .setHelpText(section.why);

    section.fields.forEach(function (f) {
      var item;

      switch (f.t) {
        case 'area':
          item = form.addParagraphTextItem();
          break;
        case 'one':
          item = form.addMultipleChoiceItem().setChoiceValues(f.opts);
          break;
        case 'many':
          item = form.addCheckboxItem().setChoiceValues(f.opts);
          if (f.other) { item.showOtherOption(true); }
          break;
        default:
          item = form.addTextItem();
      }

      item.setTitle((f.r ? '* ' : '') + f.label);
      if (f.hint) { item.setHelpText(f.hint); }

      total++;
      if (f.r) { starred++; }
    });
  });

  // Responses land in their own spreadsheet, one row per submission.
  var sheet = SpreadsheetApp.create(FORM_TITLE + ' — responses');
  form.setDestination(FormApp.DestinationType.SPREADSHEET, sheet.getId());

  var out = [
    '',
    'Built "' + FORM_TITLE + '"',
    '  ' + SECTIONS.length + ' sections, ' + total + ' questions, ' + starred + ' of them flagged as blockers.',
    '',
    'SEND THIS ONE to the electrician:',
    '  ' + form.getPublishedUrl(),
    '',
    'Edit the form:',
    '  ' + form.getEditUrl(),
    '',
    'Answers arrive here:',
    '  ' + sheet.getUrl(),
    '',
    'Next: on the Responses tab, three-dot menu, turn on email notifications,',
    'or nobody finds out when he submits it.',
    ''
  ].join('\\n');

  Logger.log(out);
  return out;
}
`;

// Apps Script takes UTF-8 happily, so the typographic characters in the copy
// survive a paste. Single quotes are the one thing to keep out of generated
// string literals, which JSON.stringify handles by quoting with double quotes.
const data = JSON.stringify(forForm, null, 2)
    .replace(new RegExp("[" + LS + PS + "]", "g"), function (m) {
      return "\\u" + m.charCodeAt(0).toString(16);
    });

fs.writeFileSync(OUT, header + data + footer);
console.log(`wrote ${path.basename(OUT)}  `
  + `${c.sections} sections, ${c.questions} questions, ${c.blockers} blockers`);
