/**
 * Electrician website intake — Google Form generator
 * -------------------------------------------------
 * GENERATED by build-gs.js from questions.js. Do not edit this file; edit
 * questions.js and re-run the build, or the web page and the Word version will
 * drift away from this one. (That has already happened once — see HANDOVER.md.)
 *
 * Builds a 17-section Google Form with 115 questions, plus a linked
 * spreadsheet that collects the answers.
 *
 * HOW TO RUN
 *   1. Go to script.google.com and click New project.
 *   2. Delete whatever is in the editor, paste this whole file in.
 *   3. Press Save, then Run. Pick buildIntakeForm if asked which function.
 *   4. Google will ask you to authorise it — it needs permission to create
 *      a form and a spreadsheet in your own Drive. Click through the
 *      "unverified app" warning via Advanced > Go to project.
 *   5. Open the Execution log. It prints three links: the form to send out,
 *      the editor, and the responses spreadsheet. The log stays empty until the
 *      run finishes, because Logger.log buffers — allow one to three minutes
 *      for roughly 132 items.
 *   6. On the Responses tab, open the three-dot menu and turn on
 *      "Get email notifications for new responses".
 *
 * Running it again builds a BRAND NEW form and sheet. Delete the old pair from
 * Drive first, or you will end up sending the client the wrong link.
 *
 * A NOTE ON REQUIRED QUESTIONS
 *   Nothing is marked required. Google Forms refuses to submit at all while
 *   a required answer is blank, and on a 115-question form filled in over
 *   several sittings that turns one unknown licence number into an abandoned
 *   form. The 36 questions that block the build are marked with a star in
 *   the title instead, and called out on the intro page. Chase those.
 */

var FORM_TITLE = 'Electrician Website — Build Brief';

var FORM_INTRO = [
  'Everything needed to build your website, in one pass.',
  '',
  'Fill in what you know. Skip anything that does not apply — a half-answer',
  'beats a blank, because "not sure" tells us what to chase.',
  '',
  'Questions marked with a star (*) are the ones that actually block the',
  'build. Four things stall these projects more than anything else:',
  'no usable job photos, no licence and insurance numbers, nobody can log',
  'in to the domain, and nobody has decided who writes the words. If you only',
  'do four sections, do 3, 9, 11 and 14.',
  '',
  'You can come back to it — when you submit, keep the "Edit your response"',
  'link that appears, and you can carry on later or correct anything.'
].join('\n');

var CONFIRMATION = [
  'Got it — thank you.',
  '',
  'Keep the "Edit your response" link above. It lets you come back and fill',
  'in anything you skipped, or fix something you got wrong, without',
  'starting again.'
].join('\n');

/**
 * t: text | area | one | many
 * r: true  -> blocks the build (rendered with a leading star)
 * other:   -> checkbox question gets Google's native "Other:" row
 */
var SECTIONS = [
  {
    "n": "01",
    "title": "Where you operate",
    "why": "Decides which licensing bodies, tax display, privacy law and consumer-rights notices apply. Everything below hangs off this.",
    "fields": [
      {
        "t": "text",
        "label": "Country",
        "r": true
      },
      {
        "t": "text",
        "label": "State, county or region",
        "r": true
      },
      {
        "t": "text",
        "label": "Languages the site must be in"
      }
    ]
  },
  {
    "n": "02",
    "title": "The business on paper",
    "why": "Goes in the footer, the legal pages and every directory listing. It has to match your other records letter for letter.",
    "fields": [
      {
        "t": "text",
        "label": "Registered legal name",
        "r": true
      },
      {
        "t": "text",
        "label": "Trading name customers actually say",
        "r": true
      },
      {
        "t": "text",
        "label": "Company or business registration number"
      },
      {
        "t": "text",
        "label": "VAT / GST / ABN / EIN number",
        "hint": "Leave blank if you're not registered — that's a normal answer, and it changes how prices are shown."
      },
      {
        "t": "one",
        "label": "Prices on the site should read",
        "r": true,
        "opts": [
          "Including tax",
          "Excluding tax",
          "No prices on the site at all"
        ]
      },
      {
        "t": "area",
        "label": "Registered address"
      },
      {
        "t": "area",
        "label": "Workshop, unit or depot address",
        "hint": "Only if it differs from the registered one."
      },
      {
        "t": "text",
        "label": "Year you started"
      },
      {
        "t": "text",
        "label": "Owner or director names, spelled as you want them printed"
      },
      {
        "t": "text",
        "label": "Who's on the books"
      }
    ]
  },
  {
    "n": "03",
    "title": "Licences, insurance, memberships",
    "why": "The single strongest trust signal on an electrician's site. Someone deciding between you and a rival looks for these before they look at anything else.",
    "fields": [
      {
        "t": "text",
        "label": "Electrical licence or registration number",
        "r": true
      },
      {
        "t": "text",
        "label": "Who issued it",
        "r": true
      },
      {
        "t": "text",
        "label": "Renewal or expiry date"
      },
      {
        "t": "many",
        "label": "Schemes and trade bodies you're a member of",
        "opts": [
          "NICEIC",
          "NAPIT",
          "ELECSA",
          "SELECT",
          "RECI",
          "Part P registered",
          "Master Electricians",
          "NECA",
          "IBEW",
          "TrustMark",
          "Which? Trusted Trader",
          "SafeContractor",
          "CHAS",
          "Constructionline"
        ],
        "other": true
      },
      {
        "t": "many",
        "label": "Qualifications worth putting on the page",
        "opts": [
          "18th Edition (BS 7671)",
          "C&G 2391 inspection & testing",
          "C&G 2919 EV charging",
          "NVQ Level 3",
          "JIB / ECS Gold Card",
          "MCS solar PV"
        ],
        "other": true
      },
      {
        "t": "text",
        "label": "Public liability — cover amount and insurer",
        "r": true
      },
      {
        "t": "text",
        "label": "Employers' liability — cover amount and insurer"
      },
      {
        "t": "text",
        "label": "Professional indemnity — cover amount"
      },
      {
        "t": "many",
        "label": "Site tickets and safety cards",
        "opts": [
          "CSCS / ECS card",
          "IPAF",
          "PASMA",
          "Working at heights",
          "Asbestos awareness",
          "Confined space",
          "First aid",
          "Manual handling"
        ]
      },
      {
        "t": "one",
        "label": "Background checks on staff",
        "hint": "Matters more than you would think to someone letting a stranger into the house.",
        "opts": [
          "Everyone is checked",
          "Some staff",
          "None",
          "Not relevant — commercial only"
        ]
      },
      {
        "t": "one",
        "label": "Can you send the logo file for each scheme you belong to?",
        "r": true,
        "hint": "Most schemes hand members a badge pack. Displaying one you're not entitled to is a real problem, so we only use what you can evidence.",
        "opts": [
          "Yes, I will send them",
          "I will need help finding them",
          "No"
        ]
      }
    ]
  },
  {
    "n": "04",
    "title": "What you actually do",
    "why": "Your top earners get a page each — that's where the enquiries come from. The rest get a line on a list.",
    "fields": [
      {
        "t": "many",
        "label": "Domestic work",
        "opts": [
          "Full and partial rewires",
          "Consumer unit / fuse board upgrades",
          "EICR inspection & testing",
          "Landlord certificates",
          "PAT testing",
          "Fault finding",
          "Sockets & switches",
          "Indoor lighting design",
          "Garden & outdoor lighting",
          "EV charger install",
          "Solar PV & battery storage",
          "Smart home / automation",
          "CCTV & alarms",
          "Data & network cabling",
          "Kitchen & bathroom electrics",
          "Underfloor heating",
          "Garage & outbuilding supply",
          "Hot tub supply",
          "New build first & second fix",
          "Electric showers & cookers"
        ],
        "other": true
      },
      {
        "t": "many",
        "label": "Commercial and industrial work",
        "opts": [
          "Commercial EICR",
          "Fire alarm install & testing",
          "Emergency lighting",
          "Three-phase work",
          "Shop & office fit-out",
          "Machinery & control panels",
          "Distribution boards",
          "Data centre / comms rooms",
          "Landlord & agent contracts",
          "Planned maintenance contracts",
          "Street & car park lighting",
          "Generators & UPS"
        ],
        "other": true
      },
      {
        "t": "area",
        "label": "Your top three to five earners, best first",
        "r": true,
        "hint": "Be honest about what pays, not what is interesting. These decide the shape of the whole site."
      },
      {
        "t": "area",
        "label": "Jobs you do NOT want the phone ringing about",
        "hint": "Just as valuable. Every wasted call costs you twenty minutes."
      },
      {
        "t": "one",
        "label": "Emergency callout",
        "opts": [
          "24/7, genuinely",
          "Evenings and weekends",
          "Business hours only",
          "No emergency work"
        ]
      },
      {
        "t": "text",
        "label": "Response time you'd put in writing, on average"
      },
      {
        "t": "one",
        "label": "EV chargers — approval status",
        "opts": [
          "Grant-approved installer (OZEV or equivalent)",
          "Manufacturer approved",
          "I install them, no formal approvals",
          "Don't do EV work"
        ]
      },
      {
        "t": "text",
        "label": "Brands you're approved or certified for"
      }
    ]
  },
  {
    "n": "05",
    "title": "Where you will travel",
    "why": "Each named town can earn its own page, and those pages are how you show up for \"electrician near me\". \"And surrounding areas\" earns nothing.",
    "fields": [
      {
        "t": "text",
        "label": "Postcode or suburb you work out of",
        "r": true
      },
      {
        "t": "area",
        "label": "Every town, suburb or postcode you cover — all of them",
        "r": true,
        "hint": "Write them out. Twenty names beats a radius, because people search the name of their own town."
      },
      {
        "t": "text",
        "label": "How far you'll travel"
      },
      {
        "t": "text",
        "label": "What you charge beyond that"
      },
      {
        "t": "text",
        "label": "Three areas you'd most like more work in"
      }
    ]
  },
  {
    "n": "06",
    "title": "Money",
    "why": "Published prices filter out tyre-kickers before they ring. Hidden prices get more calls, more of them wasted. Your call — but decide it deliberately.",
    "fields": [
      {
        "t": "one",
        "label": "Do we publish prices?",
        "r": true,
        "opts": [
          "Yes — show everything",
          "Some — fixed-price jobs only",
          "No — quote on request"
        ]
      },
      {
        "t": "text",
        "label": "Call-out fee"
      },
      {
        "t": "text",
        "label": "Hourly rate"
      },
      {
        "t": "text",
        "label": "Day rate"
      },
      {
        "t": "text",
        "label": "Minimum charge"
      },
      {
        "t": "text",
        "label": "Out-of-hours and emergency rate"
      },
      {
        "t": "area",
        "label": "Fixed-price jobs you're happy to see in print"
      },
      {
        "t": "one",
        "label": "Quotes",
        "opts": [
          "Free, always",
          "Free inside my area",
          "Chargeable, refunded against the job",
          "Chargeable"
        ]
      },
      {
        "t": "many",
        "label": "How customers can pay",
        "opts": [
          "Bank transfer",
          "Card",
          "Cash",
          "Cheque",
          "Direct debit",
          "Finance / pay monthly",
          "Trade account"
        ]
      },
      {
        "t": "text",
        "label": "Deposit terms"
      }
    ]
  },
  {
    "n": "07",
    "title": "How people reach you",
    "why": "On a phone the call button is the whole website. Everything else is there to make someone press it.",
    "fields": [
      {
        "t": "text",
        "label": "Main phone number",
        "r": true
      },
      {
        "t": "text",
        "label": "Emergency or out-of-hours number"
      },
      {
        "t": "text",
        "label": "WhatsApp number",
        "hint": "People will happily send a photo of a scorched socket at 9pm."
      },
      {
        "t": "text",
        "label": "Main email address",
        "r": true
      },
      {
        "t": "text",
        "label": "Where quote requests should land",
        "hint": "If it's a different inbox from the main one."
      },
      {
        "t": "one",
        "label": "Street address on the site",
        "r": true,
        "hint": "Plenty of electricians work from home and would rather not publish it. Town-only still works for local search.",
        "opts": [
          "Yes, full address",
          "Town or suburb only",
          "No address at all"
        ]
      },
      {
        "t": "area",
        "label": "Opening hours, written how you'd say them",
        "r": true
      },
      {
        "t": "one",
        "label": "How you'd rather be contacted",
        "opts": [
          "Phone call",
          "Enquiry form",
          "WhatsApp or text",
          "Whatever suits them"
        ]
      },
      {
        "t": "text",
        "label": "Who picks up the phone and watches the inbox"
      },
      {
        "t": "text",
        "label": "How fast do you reply to an emailed enquiry, realistically?",
        "hint": "We'll put your real number on the page. A promise you can keep beats a better-sounding one you can't."
      }
    ]
  },
  {
    "n": "08",
    "title": "Your look",
    "why": "The site should be recognisably the same outfit as the van that pulls up. Matching them is free and does a lot of work.",
    "fields": [
      {
        "t": "one",
        "label": "Logo files you can send",
        "r": true,
        "hint": "A vector file (.svg, .ai, .eps) stays sharp at any size. A logo lifted off a JPG goes fuzzy the moment it's enlarged.",
        "opts": [
          "I have the vector files",
          "Only a JPG or PNG",
          "No logo yet"
        ]
      },
      {
        "t": "text",
        "label": "Your colours"
      },
      {
        "t": "one",
        "label": "Brand guidelines document",
        "opts": [
          "Yes",
          "No"
        ]
      },
      {
        "t": "one",
        "label": "Photos of the van livery and uniform",
        "opts": [
          "Yes, can send",
          "No"
        ]
      }
    ]
  },
  {
    "n": "09",
    "title": "Photos and video",
    "why": "The commonest reason one of these builds stalls. Real photos of your own work outsell stock images by a distance — visitors can tell, even if they can't say how.",
    "fields": [
      {
        "t": "one",
        "label": "Before-and-after job photos",
        "r": true,
        "opts": [
          "Plenty, decent quality",
          "A handful of phone shots",
          "None"
        ]
      },
      {
        "t": "one",
        "label": "Do you have the customer's permission to publish those photos?",
        "r": true,
        "hint": "Inside someone's home, you need it. A one-line text asking is usually enough — keep the reply.",
        "opts": [
          "Yes, for all of them",
          "For some",
          "Haven't asked",
          "Not relevant — commercial only"
        ]
      },
      {
        "t": "one",
        "label": "Photos of you and the team",
        "hint": "A real face beats a stock model every time. It doesn't need to be a studio shot.",
        "opts": [
          "Yes",
          "No",
          "Happy to get some taken"
        ]
      },
      {
        "t": "one",
        "label": "Van or fleet photos",
        "opts": [
          "Yes",
          "No"
        ]
      },
      {
        "t": "one",
        "label": "Video footage",
        "opts": [
          "Have some",
          "Would film some",
          "None"
        ]
      },
      {
        "t": "one",
        "label": "If the photos are thin, what's the plan?",
        "r": true,
        "hint": "Decide now rather than at launch. A half-day with a photographer usually pays for itself.",
        "opts": [
          "Book a photographer",
          "I'll shoot on my phone to a brief",
          "Use stock images",
          "Not decided"
        ]
      }
    ]
  },
  {
    "n": "10",
    "title": "Proof of your work",
    "why": "Claims about quality persuade nobody. Named customers, real jobs and a written guarantee do.",
    "fields": [
      {
        "t": "text",
        "label": "Google Business Profile link"
      },
      {
        "t": "area",
        "label": "Other review profiles"
      },
      {
        "t": "text",
        "label": "Roughly how many reviews, and the average score"
      },
      {
        "t": "area",
        "label": "Testimonials you're allowed to publish",
        "hint": "Quote, first name, town. A specific one about a difficult job beats five saying \"great service\"."
      },
      {
        "t": "area",
        "label": "Three to six jobs worth writing up properly",
        "r": true,
        "hint": "For each: what was wrong, what you did, what it cost or saved them. These become the pages that win the bigger work."
      },
      {
        "t": "text",
        "label": "Commercial clients you're allowed to name"
      },
      {
        "t": "text",
        "label": "Awards or recognition"
      },
      {
        "t": "text",
        "label": "Your workmanship guarantee, word for word",
        "r": true,
        "hint": "Whatever you already tell people on the doorstep. It belongs on every page."
      }
    ]
  },
  {
    "n": "11",
    "title": "Domain, email and what exists now",
    "why": "Access is what delays launches, not building. Pointing a domain at a new site can knock out your email if nobody knows where it is hosted — so we find out first, not on launch day.",
    "fields": [
      {
        "t": "text",
        "label": "Your domain name, or the one you want",
        "r": true
      },
      {
        "t": "one",
        "label": "Who can log in and change the domain settings?",
        "r": true,
        "opts": [
          "Me, and I have the login",
          "My old web person",
          "No idea",
          "No domain yet"
        ]
      },
      {
        "t": "text",
        "label": "Where your email is hosted",
        "r": true,
        "hint": "If you genuinely do not know, write \"don't know\" — we can look it up. Guessing is what breaks things."
      },
      {
        "t": "text",
        "label": "Current website address"
      },
      {
        "t": "text",
        "label": "What it's built on and who hosts it"
      },
      {
        "t": "one",
        "label": "The current site",
        "opts": [
          "Replace it completely",
          "Keep some of the pages",
          "There is not one"
        ]
      },
      {
        "t": "one",
        "label": "Google Business Profile",
        "r": true,
        "hint": "The map listing with your reviews on it. Often worth more traffic than the website itself.",
        "opts": [
          "Claimed, I have access",
          "Claimed by someone else",
          "Not claimed",
          "Do not know what that is"
        ]
      },
      {
        "t": "area",
        "label": "Social accounts"
      },
      {
        "t": "one",
        "label": "Existing Google Analytics or Search Console",
        "opts": [
          "Yes, I have access",
          "Yes, but no access",
          "No",
          "Do not know"
        ]
      }
    ]
  },
  {
    "n": "12",
    "title": "What the site is for",
    "why": "A site built to ring the phone looks different from one built to look credible when a facilities manager checks you out. It can't be excellent at both.",
    "fields": [
      {
        "t": "one",
        "label": "The one thing the site must do",
        "r": true,
        "opts": [
          "Make the phone ring",
          "Fill in a quote form",
          "Book jobs into the diary",
          "Look credible when people check you out"
        ]
      },
      {
        "t": "many",
        "label": "Who you want more of",
        "opts": [
          "Homeowners",
          "Landlords",
          "Letting & estate agents",
          "Builders & contractors",
          "Commercial property / facilities",
          "Industrial",
          "Shops & hospitality",
          "Other trades"
        ]
      },
      {
        "t": "text",
        "label": "Enquiries a month now, and where they come from"
      },
      {
        "t": "text",
        "label": "Where you want that number"
      },
      {
        "t": "area",
        "label": "Two or three competitor sites you like, and why"
      },
      {
        "t": "area",
        "label": "Two or three you don't, and why"
      },
      {
        "t": "area",
        "label": "Why should someone pick you over the next electrician?",
        "r": true,
        "hint": "Plain words, the way you'd say it to a customer on the doorstep. This becomes the headline."
      }
    ]
  },
  {
    "n": "13",
    "title": "What the site needs to do",
    "why": "Each feature is build time and something to maintain. Pick what you'll actually use.",
    "fields": [
      {
        "t": "many",
        "label": "Features you want",
        "opts": [
          "Quote request form",
          "Photo upload of the fault",
          "Online booking / calendar",
          "WhatsApp button",
          "Live chat",
          "Sticky emergency call bar",
          "Blog / advice articles",
          "Photo gallery",
          "Service area map",
          "Finance calculator (EV / solar)",
          "Customer certificate downloads",
          "Recruitment page",
          "Newsletter signup"
        ]
      },
      {
        "t": "text",
        "label": "Job management software you already use",
        "hint": "If it has a booking widget we should plug into it rather than build a second diary you'd forget to check."
      },
      {
        "t": "area",
        "label": "What should the enquiry form ask?"
      },
      {
        "t": "text",
        "label": "Where form submissions should be emailed"
      },
      {
        "t": "one",
        "label": "Hiring?",
        "opts": [
          "Yes — want a recruitment page",
          "Maybe later",
          "No"
        ]
      },
      {
        "t": "one",
        "label": "Accessibility standard to build to",
        "hint": "Worth getting right — it also helps older customers, who are a big slice of domestic work.",
        "opts": [
          "WCAG 2.2 AA",
          "Best effort",
          "Don't know — advise me"
        ]
      }
    ]
  },
  {
    "n": "14",
    "title": "The words",
    "why": "The single most common thing a half-finished website is waiting on. Decide who writes them before anything gets built.",
    "fields": [
      {
        "t": "one",
        "label": "Who writes the text?",
        "r": true,
        "opts": [
          "I will write it",
          "You write it, I'll approve",
          "Hire a copywriter",
          "Reuse what already exists"
        ]
      },
      {
        "t": "one",
        "label": "Existing wording we can reuse — leaflets, van, old site",
        "opts": [
          "Yes, I will send it",
          "No"
        ]
      },
      {
        "t": "one",
        "label": "How it should sound",
        "opts": [
          "Friendly local tradesman",
          "Straight and professional",
          "Premium, high-end",
          "No preference"
        ]
      },
      {
        "t": "area",
        "label": "Your story",
        "r": true,
        "hint": "How you started, why you went out on your own, what you care about getting right. A few sentences in your own words is plenty — this is the About page and people do read it."
      }
    ]
  },
  {
    "n": "15",
    "title": "Legal bits",
    "why": "Small, dull, and the thing that gets forgotten until the week of launch.",
    "fields": [
      {
        "t": "many",
        "label": "Documents you already have",
        "opts": [
          "Privacy policy",
          "Cookie policy",
          "Terms & conditions",
          "Complaints procedure",
          "Cancellation notice",
          "None of these"
        ]
      },
      {
        "t": "text",
        "label": "Anything that has to appear in the footer"
      },
      {
        "t": "area",
        "label": "Your complaints procedure",
        "hint": "Several schemes require members to publish one. If you have wording from them, paste it here."
      }
    ]
  },
  {
    "n": "16",
    "title": "Budget, dates and who owns what",
    "why": "Worth being blunt about early. It changes what gets built, not whether anything does.",
    "fields": [
      {
        "t": "text",
        "label": "Budget for the build",
        "r": true
      },
      {
        "t": "text",
        "label": "Monthly budget for hosting, upkeep and advertising"
      },
      {
        "t": "text",
        "label": "When it needs to be live, and why",
        "r": true
      },
      {
        "t": "one",
        "label": "Who pays for the domain and hosting after launch?",
        "opts": [
          "Me, directly",
          "You, bill me",
          "Not decided"
        ]
      },
      {
        "t": "one",
        "label": "Do you want to change the site yourself afterwards?",
        "r": true,
        "hint": "This decides how it gets built. Retro-fitting an editor later is a rebuild.",
        "opts": [
          "Yes, regularly",
          "Occasionally",
          "No, I would rather you did it"
        ]
      },
      {
        "t": "one",
        "label": "How comfortable are you with a computer?",
        "hint": "No wrong answer. It decides how simple the editing has to be.",
        "opts": [
          "Very",
          "Average",
          "Not at all"
        ]
      },
      {
        "t": "one",
        "label": "Ongoing support",
        "opts": [
          "Monthly retainer",
          "Ad hoc, as needed",
          "I will handle it",
          "Not decided"
        ]
      },
      {
        "t": "text",
        "label": "Who signs the design off — name and email",
        "r": true,
        "hint": "One person. If your partner has a veto, name them here rather than at the end."
      }
    ]
  },
  {
    "n": "17",
    "title": "What you want to be found for",
    "why": "The phrases people type, not the ones you would use in the trade. Nobody searches \"domestic electrical contracting solutions\".",
    "fields": [
      {
        "t": "area",
        "label": "Exactly what you want to come up for"
      },
      {
        "t": "text",
        "label": "Who comes up first when you search those now?"
      },
      {
        "t": "area",
        "label": "Your name, address and phone, written exactly as they appear everywhere else",
        "r": true,
        "hint": "Letter for letter, including \"Ltd\", \"Street\" vs \"St\", and the spacing in the phone number. Inconsistency between your website, Google and the directories quietly costs you local ranking."
      }
    ]
  }
];


function buildIntakeForm() {
  var form = FormApp.create(FORM_TITLE);
  form.setDescription(FORM_INTRO);
  form.setConfirmationMessage(CONFIRMATION);
  form.setProgressBar(true);
  form.setAllowResponseEdits(true);
  form.setShowLinkToRespondAgain(false);
  form.setCollectEmail(false);

  // Workspace-only settings. Harmless to skip on a personal account.
  try { form.setRequireLogin(false); } catch (e) {}

  var starred = 0;
  var total = 0;

  SECTIONS.forEach(function (section) {
    form.addPageBreakItem()
      .setTitle(section.n + '. ' + section.title)
      .setHelpText(section.why);

    section.fields.forEach(function (f) {
      var item;

      switch (f.t) {
        case 'area':
          item = form.addParagraphTextItem();
          break;
        case 'one':
          item = form.addMultipleChoiceItem().setChoiceValues(f.opts);
          break;
        case 'many':
          item = form.addCheckboxItem().setChoiceValues(f.opts);
          if (f.other) { item.showOtherOption(true); }
          break;
        default:
          item = form.addTextItem();
      }

      item.setTitle((f.r ? '* ' : '') + f.label);
      if (f.hint) { item.setHelpText(f.hint); }

      total++;
      if (f.r) { starred++; }
    });
  });

  // Responses land in their own spreadsheet, one row per submission.
  var sheet = SpreadsheetApp.create(FORM_TITLE + ' — responses');
  form.setDestination(FormApp.DestinationType.SPREADSHEET, sheet.getId());

  var out = [
    '',
    'Built "' + FORM_TITLE + '"',
    '  ' + SECTIONS.length + ' sections, ' + total + ' questions, ' + starred + ' of them flagged as blockers.',
    '',
    'SEND THIS ONE to the electrician:',
    '  ' + form.getPublishedUrl(),
    '',
    'Edit the form:',
    '  ' + form.getEditUrl(),
    '',
    'Answers arrive here:',
    '  ' + sheet.getUrl(),
    '',
    'Next: on the Responses tab, three-dot menu, turn on email notifications,',
    'or nobody finds out when he submits it.',
    ''
  ].join('\n');

  Logger.log(out);
  return out;
}
